[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@reclaimprotocol/verifier-solidity-sdk/contracts/=node_modules/@reclaimprotocol/verifier-solidity-sdk/contracts/",
    "@chainlink/contracts/src/"

]
allow_paths = ["node_modules"]